# Dependencies
markdown:         kramdown
highighter:       true

# Permalinks
permalink:        /projects/:title

# Setup
title:            Rich Wells
tagline:          'Designer, illustrator and maker of things'
description:      'Creative Director at Yoomee. Designer, illustrator and maker of things. Christian, husband, dad, cyclist. Sheffield, UK.'
url:              http://richwells.me

author:
  name:           'Rich Wells'
  url:            https://twitter.com/richwells

paginate:         25
paginate_path:    "/projects/page:num/"

# Custom vars
version:          2.0.0

github:
  repo:           ''
baseurl:          ''
