# Dependencies
markdown:         redcarpet
highighter:       true

# Permalinks
permalink:        /blog/:title

# Setup
title:            Rich Wells
tagline:          'Designer, illustrator and maker of things'
description:      'Creative Director at Yoomee. Designer, illustrator and maker of things. Christian, husband, dad, cyclist. Sheffield, UK.'
url:              http://richwells.me

author:
  name:           'Rich Wells'
  url:            https://twitter.com/richwells

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           ''
baseurl:          'rw-jekyll'
